"""empty message

Revision ID: 023d7120c8b8
Revises: 
Create Date: 2021-07-16 08:03:42.297705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023d7120c8b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=72), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('userID', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('engineer', sa.String(length=64), nullable=False),
    sa.Column('shipyard', sa.String(length=64), nullable=True),
    sa.Column('lengthOverall', sa.Float(precision=4), nullable=True),
    sa.Column('lengthPerpendiculars', sa.Float(precision=4), nullable=True),
    sa.Column('breadth', sa.Float(precision=4), nullable=True),
    sa.Column('draft', sa.Float(precision=4), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum(name='enumtype'), nullable=True),
    sa.Column('vertical', sa.Float(precision=4), nullable=True),
    sa.Column('transversal', sa.Float(precision=4), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
